spring.application.name=entsoe-api-service
server.port=8086

# ENTSOE API
entsoe.api.token=${ENTSOE_API_TOKEN}
entsoe.api.area=${ENTSOE_AREA:10Y1001A1001A47J}

# Artemis
spring.artemis.mode=native
spring.artemis.broker-url=tcp://192.168.0.6:61616
spring.artemis.user=${ARTEMIS_USER}
spring.artemis.password=${ARTEMIS_PASSWORD}

# Spring Boot Admin
spring.boot.admin.client.url=http://192.168.0.6:8085
spring.boot.admin.client.instance.metadata.user.name=${SPRING_SECURITY_USER_NAME}
spring.boot.admin.client.instance.metadata.user.password=${SPRING_SECURITY_USER_PASSWORD}
spring.boot.admin.client.instance.service-base-url=http://192.168.0.6:8086

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.jolokia.enabled=true

# Logging
logging.file.name=/app/logs/application.log
management.endpoint.logfile.external-file=/app/logs/application.log

# Camel
camel.springboot.jmx-enabled=true
spring.main.allow-bean-definition-overriding=true